# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/twhiston/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/twhiston/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-pretarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/twhiston/Documents/Max\ 8/Packages/max-sdk/source/syphon/jit.gl.syphonclient/CMakeLists.txt))

/Users/twhiston/Documents/Max\ 8/Packages/max-sdk/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.23.1/bin/cmake -H/Users/twhiston/Documents/Max\ 8/Packages/max-sdk -B/Users/twhiston/Documents/Max\ 8/Packages/max-sdk/build
